Add internal name inlay hints
object-Object/vscode-hex-casting pull request #9
Opened 2023-07-26 16:21 UTC by Master-Bw3

- Adds setting "Show Internal Name Hints"
  - When enabled, the internal name of each pattern will be displayed as an inlay hint next to it
  - Disabled by default
  
![image](https://github.com/object-Object/vscode-hex-casting/assets/51234449/63b55919-5f38-4d3b-9359-083ddfd16965)

2023-07-26 16:42 UTC, object-Object requested changes
I like this a lot. Just a couple changes to make.

2023-07-26 16:42 UTC, object-Object commented on package.json
> +                    "hex-casting.showInternalNameHints": {
```suggestion
                    "hex-casting.inlayHints.internalName": {
```
Would prefer to follow the style of the Pylance and TypeScript extensions.

2023-07-26 16:42 UTC, object-Object commented on package.json
> +                        "description": "Controls whether the editor should display the internal name of each pattern."
```suggestion
                        "description": "Enable/disable inlay hints for internal pattern names:\n```hexpattern\nMind's Reflection/* get_caster*/\n```"
```

2023-07-26 16:42 UTC, object-Object commented on src/extension.ts
> +    showInternalNameHints = vscode.workspace.getConfiguration(rootSection).get("showInternalNameHints")!;
Not sure how this would be changed with the new key, I don't have an editor handy.

2023-07-26 16:42 UTC, object-Object commented on src/extension.ts
> +                    ...makeCompletionItem(
This is weird. Are you using the Prettier config?

2023-07-26 16:42 UTC, object-Object commented on src/extension.ts
> +        console.log("hi" + showInternalNameHints);
oops?

2023-07-26 16:42 UTC, object-Object commented on src/extension.ts
> +class PatternInlayHintsProvider implements vscode.InlayHintsProvider {
Can we combine this and the macro inlay provider? Seems like they do the same thing, it'd be easier to just have an if statement in the loop to vary which inlay is added.

2023-07-26 16:42 UTC, object-Object commented on package.json
> +                    "hex-casting.showInternalNameHints": {
Also - if you don't mind, can you add a config for the macro inlay hints while we're at it? Consistency is good. That one can default to true.

2023-07-26 16:44 UTC, object-Object commented
README also needs an update, though if you prefer I can do that when I release this.

2023-07-26 17:33 UTC, Master-Bw3 commented
Everything should be resolved now. I removed the "example" part from the setting descriptions because vscode doesn't appear to render markdown in setting descriptions.

2023-07-26 21:27 UTC, object-Object commented
Oh, it needs to be under `markdownDescription` instead.
https://github.com/golang/vscode-go/blob/3eafcb48099690dbd7f3b170b4b241020c837be7/package.json#L2672

2023-07-26 21:29 UTC, object-Object requested changes
Just looking for the markdown examples in the setting description (see earlier comment) then it'll be good to merge.

2023-07-27 04:58 UTC, Master-Bw3 commented
the markdown support is *extermely* limited so the best I could do is this: 
![image](https://github.com/object-Object/vscode-hex-casting/assets/51234449/1f25d863-3407-4479-a1ec-026cd1f45b7f)

2023-07-27 12:09 UTC, object-Object approved these changes

2023-07-27 12:09 UTC, merged